Decommission handler
sensu-plugins/sensu-plugins-chef pull request #11
Opened 2015-12-14 00:00 UTC by psyhomb

I have modified a bit `handler-chef-node.rb` handler and added some additional functionalities like Flapjack support and possibility to disable chef check and to trigger deletion only if keepalive interval reach certain value (handled through Sensu filter feature). 
Also in order to suppress some ridley WARN messages (e.g. WARN -- : Terminating task: type=:finalizer, meta={:method_name=>:shutdown}, status=:receiving) a logger severity level has been changed to ERROR.

Cheers

2016-04-27 02:29 UTC, mattyjones commented
@psyhomb 

Can you please add some tests for this as well as update the CHANGELOG please.

2016-05-08 13:00 UTC, psyhomb commented
@mattyjones 

Can you please be a little bit more specific about tests?

Anyhow I'm using this handler in the production for quite some time and everything is running smoothly and without any issues.

I have updated the CHANGELOG as well

Cheers

2017-05-29 05:34 UTC, majormoses requested changes

2017-05-29 05:34 UTC, majormoses commented on CHANGELOG.md
> +## [0.0.7] - 2016-05-08
remove the version, we will bump this when we are ready to release.

2017-05-29 05:34 UTC, majormoses commented on bin/decomm.rb
> +    rescue Celluloid::Error
Pretty sure if you move `Celluloid.boot` to before it works without rescue, (it does for the other checks that now use ridley).

2017-05-29 05:34 UTC, majormoses commented on bin/decomm.rb
> +  def filter; end
why is this needed?

2017-06-25 01:16 UTC, majormoses commented on bin/decomm.rb
> +  def filter; end
I am guessing this is to avoid the built in filter...

2017-07-04 03:28 UTC, majormoses commented
closing due to inactivity, please reply back if you intend to see this through to completion and we can re-open.

2017-07-04 03:28 UTC, closed without merging